sudo: false

language: go

go:
  - 1.5

branches:
  only:
    - master

before_script: |-
  wget -O consul.zip -q https://dl.bintray.com/mitchellh/consul/0.5.2_linux_amd64.zip
  unzip consul.zip
  mv consul ~/bin/

script: make updatedeps test testrace
